language: python

python:
  - 2.7
  - 3.5
  - 3.6

install:
  - pip install poetry
  - poetry install

script:
  - pytest

after_success:
  - pip install coveralls
  - coveralls

notifications:
  email:
    on_success: never
    on_failure: change
